#ifndef __V10_ULTRA_RGB_INDEX__
#define __V10_ULTRA_RGB_INDEX__

#define RGB_MATRIX_LED_COUNT (88)

#define CAPS_LOCK_INDEX 48
// #define NUM_LOCK_INDEX  255
#define BT1_LED_INDEX 17
#define BT2_LED_INDEX 18
#define BT3_LED_INDEX 19
#define PPT_LED_INDEX 20
#define BAT_LOW_INDEX 81
#define BAT_LOW_INDEX1 83
#define BAT_LED_INDEX 17

#define RGB_TEST_RIGHT_KEY 88
#define RGB_TEST_HOME_KEY 62
#define RGB_TEST_FN_KEY 83

#endif
