#ifndef __V2_ULTRA_RGB_INDEX__
#define __V2_ULTRA_RGB_INDEX__

#define RGB_MATRIX_LED_COUNT (67)

#define CAPS_LOCK_INDEX 30
#define BT1_LED_INDEX 16
#define BT2_LED_INDEX 17
#define BT3_LED_INDEX 18
#define PPT_LED_INDEX 19
#define BAT_LOW_INDEX 60

#define RGB_TEST_RIGHT_KEY 66
#define RGB_TEST_HOME_KEY 43
#define RGB_TEST_FN_KEY 63

#endif
