#ifndef __Q6_ULTRA_RGB_INDEX__
#define __Q6_ULTRA_RGB_INDEX__

#define RGB_MATRIX_LED_COUNT (108)

#define CAPS_LOCK_INDEX 61
#define NUM_LOCK_INDEX 37
#define BT1_LED_INDEX 21
#define BT2_LED_INDEX 22
#define BT3_LED_INDEX 23
#define PPT_LED_INDEX 24
#define BAT_LOW_INDEX 97
#define BAT_LED_INDEX 21

#define RGB_TEST_RIGHT_KEY 105
#define RGB_TEST_HOME_KEY 36
#define RGB_TEST_FN_KEY 101

#endif
