#ifndef __V1_ULTRA_RGB_INDEX__
#define __V1_ULTRA_RGB_INDEX__

#define RGB_MATRIX_LED_COUNT (97)

#define CAPS_LOCK_INDEX 51
#define NUM_LOCK_INDEX 30
#define BT1_LED_INDEX 17
#define BT2_LED_INDEX 18
#define BT3_LED_INDEX 19
#define PPT_LED_INDEX 20
#define BAT_LOW_INDEX 88

#define RGB_TEST_RIGHT_KEY 95
#define RGB_TEST_HOME_KEY 14
#define RGB_TEST_FN_KEY 91

#endif
