#ifndef __V1_ULTRA_RGB_INDEX__
#define __V1_ULTRA_RGB_INDEX__

#define RGB_MATRIX_LED_COUNT (82)

#define CAPS_LOCK_INDEX 45
// #define NUM_LOCK_INDEX  255
#define BT1_LED_INDEX 16
#define BT2_LED_INDEX 17
#define BT3_LED_INDEX 18
#define PPT_LED_INDEX 19
#define BAT_LOW_INDEX 75

#define RGB_TEST_RIGHT_KEY 81
#define RGB_TEST_HOME_KEY 58
#define RGB_TEST_FN_KEY 77

#endif
