#ifndef __RS45_RGB_INDEX__
#define __RS45_RGB_INDEX__

#define RGB_MATRIX_LED_COUNT (87)

#define CAPS_LOCK_INDEX 50
// #define NUM_LOCK_INDEX  255
#define BT1_LED_INDEX 17
#define BT2_LED_INDEX 18
#define BT3_LED_INDEX 19
#define PPT_LED_INDEX 20
#define BAT_LOW_INDEX 79
// #define FN_WIN_LOCK_INDEX 86

#define RGB_TEST_RIGHT_KEY 87
#define RGB_TEST_HOME_KEY 32
#define RGB_TEST_FN_KEY 83

#endif
